#!/bin/sh

case "$(file -Lb --mime-type -- "$1")" in
    image/*)
        # chafa -f sixel -s "$2x$3" --animate off --polite on "$1"
        chafa -f sixel --size "50x50" --view-size "$2x$3" --animate off --polite on "$1"
        exit 1
        ;;
    *)
        cat "$1"
        ;;
esac
