#!/bin/sh

term=foot
menu=fuzzel
browser=firefox

# input
riverctl set-repeat 45 150
riverctl keyboard-layout -options 'grp:lalt_lshift_toggle' 'us(dvorak),ru'
layout=0

# spawn
riverctl map -layout $layout normal Super Return spawn $term
riverctl map -layout $layout normal Super D spawn $menu
riverctl map -layout $layout normal Super+Shift Return spawn $browser

riverctl map -layout $layout normal None print spawn "grim - | satty --filename - --fullscreen --output-filename ~/Pictures/Screenshots/satty-$(date '+%Y%m%d-%H:%M:%S').png"


# close
riverctl map -layout $layout normal Super Q close
riverctl map -layout $layout normal Super+Shift E exit
# TODO: reload river bind (run init)

# tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map -layout $layout normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map -layout $layout normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map -layout $layout normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map -layout $layout normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map -layout $layout normal Super 0 set-focused-tags $all_tags
riverctl map -layout $layout normal Super+Shift 0 set-view-tags $all_tags

# view cycling
riverctl map -layout $layout normal Super L focus-view next
riverctl map -layout $layout normal Super H focus-view previous

riverctl map -layout $layout normal Super+Shift L swap next
riverctl map -layout $layout normal Super+Shift H swap previous

riverctl map -layout $layout normal Super T zoom

# moving/resizing views
riverctl map -layout $layout normal Super+Alt H move left 100
riverctl map -layout $layout normal Super+Alt J move down 100
riverctl map -layout $layout normal Super+Alt K move up 100
riverctl map -layout $layout normal Super+Alt L move right 100

riverctl map -layout $layout normal Super+Alt+Shift H resize horizontal -100
riverctl map -layout $layout normal Super+Alt+Shift J resize vertical 100
riverctl map -layout $layout normal Super+Alt+Shift K resize vertical -100
riverctl map -layout $layout normal Super+Alt+Shift L resize horizontal 100

riverctl map -layout $layout normal Super+Alt+Control H snap left
riverctl map -layout $layout normal Super+Alt+Control J snap down
riverctl map -layout $layout normal Super+Alt+Control K snap up
riverctl map -layout $layout normal Super+Alt+Control L snap right

riverctl map -layout $layout normal Super Space toggle-float
riverctl map -layout $layout normal Super F toggle-fullscreen

# mouse binds
riverctl map -layout $layout-pointer normal Super BTN_LEFT move-view
riverctl map -layout $layout-pointer normal Super BTN_RIGHT resize-view
riverctl map -layout $layout-pointer normal Super BTN_MIDDLE toggle-float

# multiple monitor setup
riverctl map -layout $layout normal Super Period focus-output next
riverctl map -layout $layout normal Super Comma focus-output previous

riverctl map -layout $layout normal Super+Shift Period send-to-output next
riverctl map -layout $layout normal Super+Shift Comma send-to-output previous

# tiling
riverctl map -layout $layout normal Super J send-layout-cmd rivertile "main-ratio -0.05"
riverctl map -layout $layout normal Super K send-layout-cmd rivertile "main-ratio +0.05"

riverctl map -layout $layout normal Super+Shift J send-layout-cmd rivertile "main-count -1"
riverctl map -layout $layout normal Super+Shift K send-layout-cmd rivertile "main-count +1"

# layout
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 &

riverctl map -layout $layout normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map -layout $layout normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map -layout $layout normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map -layout $layout normal Super Left  send-layout-cmd rivertile "main-location left"

# passthrough mode

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

riverctl map -layout $layout normal Super F11 enter-mode passthrough
riverctl map -layout $layout passthrough Super F11 enter-mode normal

# media keys
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    # riverctl map -layout $layout $mode None XF86Eject spawn 'eject -T'

    riverctl map -layout $layout $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume 0 +1%'
    riverctl map -layout $layout $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume 0 -1%'
    riverctl map -layout $layout $mode None XF86AudioMute         spawn 'pactl set-sink-mute 0 toggle'

    riverctl map -layout $layout $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map -layout $layout $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map -layout $layout $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map -layout $layout $mode None XF86AudioNext  spawn 'playerctl next'

    riverctl map -layout $layout $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map -layout $layout $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# rules
riverctl rule-add -app-id 'float*' -title 'foo' float

riverctl rule-add -app-id "bar" csd

# vis
riverctl border-width 0
# riverctl background-color 0x002b36
# riverctl border-color-focused 0x93a1a1
# riverctl border-color-unfocused 0x586e75

swaybg -m fill -i ~/.wallpapers/vista_dark_3.jpg &
